# Generated by Django 5.2.12 on 2026-03-17 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastPayRecord',
            fields=[
                ('last_pay_record_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(max_length=50, unique=True)),
                ('lp_status', models.CharField(choices=[('PENDING', 'Pending'), ('FINALIZED', 'Finalized'), ('RELEASED', 'Released'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('emp_id', models.CharField(db_index=True, max_length=50)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_status', models.CharField(max_length=5)),
                ('bank_id', models.CharField(max_length=50)),
                ('comp_id', models.CharField(max_length=50)),
                ('department_id', models.CharField(db_index=True, max_length=50)),
                ('position', models.CharField(db_index=True, max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_days_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basic_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_day', models.DateTimeField()),
                ('employee_start_date', models.DateTimeField()),
                ('employee_end_date', models.DateTimeField()),
                ('cut_off_start_date', models.DateTimeField()),
                ('cut_off_end_date', models.DateTimeField()),
                ('last_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lp_total_ot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lp_total_leave', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lp_total_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lp_total_absents', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lp_total_payables', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lp_total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lp_total_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lp_total_tm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_by', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('disapprove_remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Last Pay Record',
                'verbose_name_plural': 'Last Pay Records',
                'db_table': 'lp_last_pay_records',
            },
        ),
        migrations.CreateModel(
            name='AllowanceTable',
            fields=[
                ('allowance_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('allowance_desc', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_pay_record_id', models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
                'db_table': 'lp_allowance_table',
            },
        ),
        migrations.CreateModel(
            name='AdditionalsType',
            fields=[
                ('ad_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('addtl_type', models.CharField(choices=[('P', 'Payable'), ('D', 'Deduction')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_pay_record_id', models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': 'Additional Detail',
                'verbose_name_plural': 'Additional Details',
                'db_table': 'lp_addtl_details',
            },
        ),
        migrations.CreateModel(
            name='LeaveMonthlyDetail',
            fields=[
                ('leave_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cut_off_date', models.CharField(max_length=50)),
                ('days_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_pay_record_id', models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': 'Leave Monthly Detail',
                'verbose_name_plural': 'Leave Monthly Details',
                'db_table': 'lp_leave_monthly_details',
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('loan_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_granted', models.DateTimeField()),
                ('loan_description', models.CharField(max_length=255)),
                ('total_loan_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_pay_record_id', models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': 'Loan Detail',
                'verbose_name_plural': 'Loan Details',
                'db_table': 'lp_loan_details',
            },
        ),
        migrations.CreateModel(
            name='Month13SalaryDetail',
            fields=[
                ('tm_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coverage_month', models.CharField(max_length=50)),
                ('total_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('days_absent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_pay_record_id', models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': '13th Month Salary Detail',
                'verbose_name_plural': '13th Month Salary Details',
                'db_table': 'lp_month13_salary_details',
            },
        ),
        migrations.CreateModel(
            name='OvertimeDetail',
            fields=[
                ('overtime_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord')),
            ],
            options={
                'verbose_name': 'Overtime Detail',
                'verbose_name_plural': 'Overtime Details',
                'db_table': 'lp_overtime_details',
            },
        ),
    ]
