# Generated by Django 4.2.16 on 2026-03-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimedetail',
            options={'managed': False, 'verbose_name': 'Overtime Detail', 'verbose_name_plural': 'Overtime Details'},
        ),
    ]
