# Generated by Django 4.2.16 on 2026-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wepay", "0002_alter_overtimedetail_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="overtimedetail",
            options={
                "verbose_name": "Overtime Detail",
                "verbose_name_plural": "Overtime Details",
            },
        ),
        migrations.AlterField(
            model_name="additionalstype",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="allowancetable",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="bank_id",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="basic_pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="comp_id",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="daily_rate",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="department_id",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="emp_status",
            field=models.CharField(default="Reg", max_length=5),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="last_pay",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_absents",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_allowance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_deductions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_leave",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_loans",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_ot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_payables",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="lp_total_tm",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="net_pay",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="lastpayrecord",
            name="position",
            field=models.CharField(db_index=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="leavemonthlydetail",
            name="remaining",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="loandetail",
            name="paid_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loandetail",
            name="total_loan_amt",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="month13salarydetail",
            name="total_amt",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
