# Generated by Django 4.2.16 on 2026-03-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0004_sync_models_with_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimedetail',
            name='ot_type',
            field=models.CharField(default='Regular', max_length=20),
        ),
    ]
