# Generated by Django 4.2.16 on 2026-03-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0005_lastpayrecord_emp_type_overtimedetail_ot_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='cut_off_date',
            field=models.DateTimeField(),
        ),
    ]
