# Generated by Django 4.2.16 on 2026-03-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0006_lastpayrecord_emp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpayrecord',
            name='emp_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='overtimedetail',
            name='last_pay_record_id',
            field=models.ForeignKey(db_column='last_pay_record_id', on_delete=django.db.models.deletion.CASCADE, to='wepay.lastpayrecord'),
        ),
    ]
