# Generated by Django 4.2.16 on 2026-03-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0006_fix_leave_monthly_detail_fields'),
        ('wepay', '0008_sync_existing_tables'),
    ]

    operations = [
    ]
