# Generated by Django 4.2.16 on 2026-03-18 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0009_merge_20260318_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimedetail',
            name='date_granted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='end_cut_off_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='start_cut_off_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='date_granted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
