# Generated by Django 4.2.16 on 2026-03-19 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0010_add_date_granted_to_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month13salarydetail',
            name='coverage_month',
        ),
        migrations.AddField(
            model_name='month13salarydetail',
            name='tm_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='month13salarydetail',
            name='tm_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
