# Generated by Django 5.2.12 on 2026-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0011_update_month13_coverage_month_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpayrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastpayrecord',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastpayrecord',
            name='disapproved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastpayrecord',
            name='disapproved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
