# Generated by Django 5.2.12 on 2026-03-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0012_lastpayrecord_approved_at_lastpayrecord_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetable',
            name='allowance_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='lastpayrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('lp_status__in', ['PENDING', 'DRAFT'])), fields=('emp_id',), name='unique_active_quit_claim_per_employee'),
        ),
    ]
