# Generated by Django 5.2.12 on 2026-03-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0013_rename_lp_total_loans_lastpayrecord_lp_total_loan_balance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lastpayrecord',
            name='unique_active_quit_claim_per_employee',
        ),
        migrations.RenameField(
            model_name='lastpayrecord',
            old_name='lp_total_loans',
            new_name='lp_total_loan_balance',
        ),
    ]
