# Generated by Django for MariaDB - Fix duplicate prevention to allow status updates

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('wepay', '0014_remove_lastpayrecord_unique_active_quit_claim_per_employee_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS prevent_duplicate_quit_claims_update
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS prevent_duplicate_quit_claims
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER prevent_duplicate_quit_claims
            BEFORE INSERT ON lp_last_pay_records
            FOR EACH ROW
            BEGIN
                IF NEW.lp_status IN ('PENDING', 'DRAFT') THEN
                    IF EXISTS (
                        SELECT 1 FROM lp_last_pay_records 
                        WHERE emp_id = NEW.emp_id 
                        AND lp_status IN ('PENDING', 'DRAFT')
                    ) THEN
                        SIGNAL SQLSTATE '45000'
                        SET MESSAGE_TEXT = 'Employee already has an active quit claim';
                    END IF;
                END IF;
            END
            """,
            reverse_sql="DROP TRIGGER IF EXISTS prevent_duplicate_quit_claims"
        )
    ]
