# Generated by Django for MariaDB - Remove trigger blocking status updates

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('wepay', '0015_fix_duplicate_prevention_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS prevent_modifications_to_finalized
            """,
            reverse_sql=""
        )
    ]
