# Generated by Django 5.2.12 on 2026-04-06 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0017_remove_date_granted_from_loan_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalstype',
            name='is_deletable',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
