# Generated by Django 5.2.12 on 2026-04-07 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0020_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month13salarydetail',
            name='coverage_month',
            field=models.IntegerField(),
        )
    ]
