# Generated by Django 5.2.12 on 2026-04-07 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0021_change_coverage_month_to_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastpayrecord',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='lastpayrecord',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='lastpayrecord',
            name='last_day',
        ),
        migrations.AddField(
            model_name='loandetail',
            name='balance_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='additionalstype',
            name='ad_type_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lastpayrecord',
            name='last_pay_record_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lastpayrecord',
            name='ref_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='leave_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month13salarydetail',
            name='days_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month13salarydetail',
            name='tm_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='overtimedetail',
            name='overtime_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
