# Generated by Django 5.2.12 on 2026-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0022_change_days_absent_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='days_used',
            field=models.IntegerField(default=0),
        ),
    ]
