# Generated by Django 5.2.12 on 2026-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0023_change_days_used_to_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemonthlydetail',
            name='end_cut_off_date',
        ),
        migrations.RemoveField(
            model_name='leavemonthlydetail',
            name='start_cut_off_date',
        ),
        migrations.AddField(
            model_name='leavemonthlydetail',
            name='coverage_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
