# Generated by Django 5.2.12 on 2026-04-07 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0024_simplify_leave_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemonthlydetail',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='month13salarydetail',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='coverage_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='month13salarydetail',
            name='coverage_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
