# Generated by Django 5.2.12 on 2026-04-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0025_leavemonthlydetail_year_month13salarydetail_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalstype',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalstype',
            name='is_confidential',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='days_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leavemonthlydetail',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
