# Generated by Django 5.2.12 on 2026-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0026_add_confidential_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstype',
            name='created_by_role',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
