# Generated by Django 5.2.12 on 2026-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0027_change_created_by_role_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalstype',
            name='role_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
