# Generated by Django 5.2.12 on 2026-04-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0028_add_role_id_field'),
    ]

    operations = [
        # This migration marks the is_confidential field as already updated to BooleanField
        # and created_by_role field as already added. No actual changes needed.
    ]
