# Generated by Django 5.2.12 on 2026-04-10 04:38

from django.db import migrations, models


def convert_role_strings_to_integers(apps, schema_editor):
    """Convert string role names to integer IDs"""
    AdditionalsType = apps.get_model('wepay', 'AdditionalsType')
    role_mapping = {
        'superadmin': 1,
        'finance': 2,
        'hr': 3,
        'manager': 4,
    }
    
    for item in AdditionalsType.objects.all():
        if item.created_by_role in role_mapping:
            item.created_by_role = role_mapping[item.created_by_role]
            item.save()


def revert_role_integers_to_strings(apps, schema_editor):
    """Revert integer role IDs to string names"""
    AdditionalsType = apps.get_model('wepay', 'AdditionalsType')
    reverse_mapping = {
        1: 'superadmin',
        2: 'finance',
        3: 'hr',
        4: 'manager',
    }
    
    for item in AdditionalsType.objects.all():
        if item.created_by_role in reverse_mapping:
            item.created_by_role = reverse_mapping[item.created_by_role]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wepay', '0029_mark_confidential_field_as_updated'),
    ]

    operations = [
        # Convert existing string data to integers before changing field type
        migrations.RunPython(convert_role_strings_to_integers, revert_role_integers_to_strings),
        # Change field type from CharField to IntegerField
        migrations.AlterField(
            model_name='additionalstype',
            name='created_by_role',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
